const Strings = {
	en: {
		AppName: 'ExamBook',
		Getstarted: 'Get started',

		// Header
		HeaderTitle: 'Cognitive Cloud',
		Step: 'Step',
		Of: 'of',

		// Login screen
		WelcomeTo: 'Welcome to',
		LetsGetLearning: "Let's get your learning started",
		MobileNumber: 'Mobile Number',
		Enter10Digit: 'Enter 10-digit number',
		GetOTP: 'Get OTP',
		AgreePart1: 'By continuing, you agree to our ',
		AgreePart2: ' and ',
		AgreePart3: '',
		TermsOfService: 'Terms of Service',
		PrivacyPolicy: 'Privacy Policy',
		InvalidNumber: 'Invalid Number',
		EnterValid10Digit: 'Please enter a valid 10-digit mobile number',

		WelcomeBack: 'Welcome back',
		EmailLabel: 'Email',
		EmailPlaceholder: 'you@example.com',
		PasswordLabel: 'Password',
		PasswordPlaceholder: 'Enter your password',
		ForgotPassword: 'Forgot password?',
		LoginButton: 'Log in',
		NoAccount: "Don't have an account?",
		IndividualType: 'Individual',
		GovernmentType: 'Government',

		// OTP Screen
		VerificationCode: 'Verification Code',
		EnterCodeSent: 'Enter the code sent to',
		DidntReceiveCode: "Didn't receive code?",
		Resend: 'Resend',
		ResendIn: 'Resend in',
		VerifyProceed: 'Verify & Proceed',
		OTPResent: 'OTP Sent',
		OTPResentDesc: 'A verification code has been resent to your number.',
		InvalidOTP: 'Invalid OTP',
		PleaseEnter4Digit: 'Please enter a 4-digit verification code.',

		VerifyOTP: 'Verify OTP',
		EnterOTP: 'Enter the 4-digit code sent to your mobile number',
		ResendCode: 'Resend Code',
		Submit: 'Submit',

		// Select Language
		ChooseLanguage: 'Choose your language',
		YourJourney: 'Your Journey,\nYour Language.',
		ChooseLanguageDescription: 'Select the primary language for your AI tutor and learning materials. You can change this anytime.',
		English: 'English',
		EnglishSubtitle: 'Global standard for science and mathematics modules.',
		Hindi: 'हिंदी',
		HindiSubtitle: 'Comprehensive support for concepts in Hindi medium.',
		Continue: 'Continue',
		BilingualPart1: 'Prefer both? You can enable ',
		BilingualPart2: ' later.',
		BilingualText: 'Bilingual Mode',

		// Select Class
		WelcomeToCloud: 'Welcome to the',
		Cloud: 'Cloud!',
		TutorDescription: "I'm your AI tutor. To get started, let's find your level. Which class are you currently in?",
		ClassLabel: 'CLASS',
		ContinueToBoards: 'Continue to Boards',
		FooterNote: 'You can change this anytime from your profile settings.',

		// Select Board
		ChooseEducationalPath: 'Choose your\nEducational Path',
		BoardDescription: "We'll tailor your AI tutoring experience and practice materials based on your specific school board curriculum.",
		Selected: 'Selected',
		SelectBoard: 'Select Board',
		NotSureTitle: 'Not sure which one to pick?',
		NotSureDesc: 'Most Indian private schools follow CBSE. You can always change this later in your profile settings if you move to a different school or board.',
		CompareBoards: 'Compare Boards',
		SelectionAffects: 'Selection affects Lesson content & AI tutoring style.',
		SkipForNow: 'Skip for now',

		CBSETitle: 'CBSE',
		CBSEDesc: 'Central Board of Secondary Education. National standard with a focus on NCERT curriculum.',
		ICSETitle: 'ICSE',
		ICSEDesc: 'Indian Certificate of Secondary Education. Comprehensive and in-depth syllabus approach.',
		RBSETitle: 'RBSE',
		RBSEDesc: 'Rajasthan Board of Secondary Education. State-specific curriculum excellence.',

		// Toast
		OnboardingComplete: 'Onboarding Complete',
		WelcomeToCognitiveCloud: 'Welcome to Cognitive Cloud!',

		// common
		Back: 'Back',
		Next: 'Next',

		// Dashboard
		Hello: 'Hello',
		LetsLearnSomethingNew: 'Let’s learn something new today.',
		DayStreak: 'Day Streak!',
		FocusMasterBadge: 'Keep it up to unlock the "Focus Master" badge.',
		DailyGoal: 'Daily Goal',
		MinsCompleted: 'mins completed',
		StuckOnConcept: 'Stuck on a concept?',
		AITutorReady: "Your AI Tutor is ready to explain Algebra or Newton's Laws in a way you'll love.",
		AskAITutor: 'Ask AI Tutor',
		YourSubjects: 'Your Subjects',
		ViewAll: 'View All',
		RecommendedForYou: 'Recommended for You',
		Home: 'Home',
		Study: 'Study',
		AITutor: 'AI Tutor',
		Progress: 'Progress',

		// Progress Screen
		MyRewards: 'My Rewards',
		Points: 'pts',
		GreatJob: 'Great job',
		TopPercent: "You're in the top 5% of students this week. Keep up the momentum to unlock the Master Explorer badge!",
		ClaimDailyBonus: 'Claim Daily Bonus',
		Level: 'LEVEL',
		XPToLevel: 'XP to Level',
		MyBadges: 'My Badges',
		BadgesUnlocked: 'badges unlocked',
		SevenDayStreak: '7-Day Streak',
		UnlockedDaysAgo: 'Unlocked 2 days ago',
		MathWhiz: 'Math Whiz',
		PercentInGeometry: '100% in Geometry',
		DoubtDestroyer: 'Doubt Destroyer',
		ResolvedDoubts: 'Resolved 50 doubts',
		Solution: 'Solution',
		SolutionRead: 'Read solutions',
		LeaderboardPreview: 'Leaderboard Preview',
		ViewFullLeaderboard: 'View Full Leaderboard',
		You: 'You',
		RisingStar: 'Rising Star',

		// Profile Screen
		EditProfile: 'Edit Profile',
		ChangeProfilePicture: 'Change Profile Picture',
		FullName: 'Full Name',
		FullNamePlaceholder: 'Enter your full name',
		EmailAddress: 'Email Address',
		ProfileEmailPlaceholder: 'Enter your email',
		MobileNumberLabel: 'Mobile Number',
		MobilePlaceholder: 'Enter your mobile number',
		CurrentClass: 'Current Class',
		EducationalBoard: 'Educational Board',
		LanguagePreference: 'Language Preference',
		ProfilePrivacyNote: 'Your profile information is used to personalize your learning journey and AI Tutor responses. We never share your contact details.',
		SaveChanges: 'Save Changes',
		Logout: 'Logout',
	},
	hi: {
		AppName: 'एग्जामबुक',
		Getstarted: 'शुरू करें',

		// Header
		HeaderTitle: 'कॉग्निटिव क्लाउड',
		Step: 'कदम',
		Of: 'का',

		// Login screen
		WelcomeTo: 'स्वागत है',
		LetsGetLearning: 'आइए आपकी शिक्षा शुरू करें',
		MobileNumber: 'मोबाइल नंबर',
		Enter10Digit: '10 अंकों का नंबर दर्ज करें',
		GetOTP: 'ओटीपी प्राप्त करें',
		AgreePart1: 'जारी रखकर, आप हमारी ',
		AgreePart2: ' और ',
		AgreePart3: ' से सहमत हैं',
		TermsOfService: 'सेवा की शर्तों',
		PrivacyPolicy: 'गोपनीयता नीति',
		InvalidNumber: 'अमान्य नंबर',
		EnterValid10Digit: 'कृपया एक मान्य 10-अंकीय मोबाइल नंबर दर्ज करें',

		WelcomeBack: 'वापस स्वागत है',
		EmailLabel: 'ईमेल',
		EmailPlaceholder: 'you@example.com',
		PasswordLabel: 'पासवर्ड',
		PasswordPlaceholder: 'अपना पासवर्ड दर्ज करें',
		ForgotPassword: 'पासवर्ड भूल गए?',
		LoginButton: 'लॉग इन करें',
		NoAccount: "क्या आपके पास खाता नहीं है?",
		IndividualType: 'व्यक्तिगत',
		GovernmentType: 'सरकारी',

		// OTP Screen
		VerificationCode: 'सत्यापन कोड',
		EnterCodeSent: 'में भेजा गया कोड दर्ज करें',
		DidntReceiveCode: 'कोड प्राप्त नहीं हुआ?',
		Resend: 'पुनः भेजें',
		ResendIn: 'पुनः भेजें',
		VerifyProceed: 'सत्यापित करें और आगे बढ़ें',
		OTPResent: 'ओटीपी भेजा गया',
		OTPResentDesc: 'आपके नंबर पर एक सत्यापन कोड पुनः भेज दिया गया है।',
		InvalidOTP: 'अमान्य ओटीपी',
		PleaseEnter4Digit: 'कृपया 4-अंकीय सत्यापन कोड दर्ज करें।',

		VerifyOTP: 'ओटीपी सत्यापित करें',
		EnterOTP: 'आपके मोबाइल नंबर पर भेजा गया 4-अंकीय कोड दर्ज करें',
		ResendCode: 'कोड पुनः भेजें',
		Submit: 'जमा करें',

		// Select Language
		ChooseLanguage: 'अपनी भाषा चुनें',
		YourJourney: 'आपकी यात्रा,\nआपकी भाषा।',
		ChooseLanguageDescription: 'अपने एआई ट्यूटर और सीखने की सामग्री के लिए प्राथमिक भाषा चुनें। आप इसे कभी भी बदल सकते हैं।',
		English: 'English',
		EnglishSubtitle: 'विज्ञान और गणित मॉड्यूल के लिए वैश्विक मानक।',
		Hindi: 'हिंदी',
		HindiSubtitle: 'हिंदी माध्यम में अवधारणाओं के लिए व्यापक समर्थन।',
		Continue: 'जारी रखें',
		BilingualPart1: 'दोनों पसंद हैं? आप बाद में ',
		BilingualPart2: ' सक्षम कर सकते हैं।',
		BilingualText: 'द्विभाषी मोड',

		// Select Class
		WelcomeToCloud: 'में आपका स्वागत है',
		Cloud: 'क्लाउड',
		TutorDescription: "मैं आपका एआई ट्यूटर हूं। शुरू करने के लिए, आइए आपका स्तर जानें। आप अभी किस कक्षा में हैं?",
		ClassLabel: 'कक्षा',
		ContinueToBoards: 'बोर्ड पर जारी रखें',
		FooterNote: 'आप इसे अपने प्रोफाइल सेटिंग्स से कभी भी बदल सकते हैं।',

		// Select Board
		ChooseEducationalPath: 'अपना शैक्षिक\nपथ चुनें',
		BoardDescription: 'हम आपके स्कूल बोर्ड के पाठ्यक्रम के आधार पर आपके एआई ट्यूशन अनुभव और अभ्यास सामग्री को तैयार करेंगे।',
		Selected: 'चयनित',
		SelectBoard: 'बोर्ड चुनें',
		NotSureTitle: 'निश्चित नहीं हैं कि किसे चुनें?',
		NotSureDesc: 'अधिकांश भारतीय निजी स्कूल सीबीएसई का पालन करते हैं। यदि आप किसी दूसरे स्कूल या बोर्ड में जाते हैं तो आप बाद में अपनी प्रोफाइल सेटिंग में इसे हमेशा बदल सकते हैं।',
		CompareBoards: 'बोर्डों की तुलना करें',
		SelectionAffects: 'चयन पाठ सामग्री और एआई ट्यूशन शैली को प्रभावित करता है।',
		SkipForNow: 'अभी छोड़ें',

		CBSETitle: 'सीबीएसई',
		CBSEDesc: 'केंद्रीय माध्यमिक शिक्षा बोर्ड। एनसीईआरटी पाठ्यक्रम पर केंद्रित राष्ट्रीय मानक।',
		ICSETitle: 'आईसीएसई',
		ICSEDesc: 'भारतीय माध्यमिक शिक्षा प्रमाणपत्र। व्यापक और गहन पाठ्यक्रम दृष्टिकोण।',
		RBSETitle: 'आरबीएसई',
		RBSEDesc: 'राजस्थान माध्यमिक शिक्षा बोर्ड। राज्य-विशिष्ट पाठ्यक्रम उत्कृष्टता।',

		// Toast
		OnboardingComplete: 'ऑनबोर्डिंग पूर्ण',
		WelcomeToCognitiveCloud: 'कॉग्निटिव क्लाउड में आपका स्वागत है!',

		// common
		Back: 'पीछे',
		Next: 'आगे',

		// Dashboard
		Hello: 'नमस्ते',
		LetsLearnSomethingNew: 'आज कुछ नया सीखते हैं।',
		DayStreak: 'दिन का सिलसिला!',
		FocusMasterBadge: '"फोकस मास्टर" बैज को अनलॉक करने के लिए इसे जारी रखें।',
		DailyGoal: 'दैनिक लक्ष्य',
		MinsCompleted: 'मिनट पूरे हुए',
		StuckOnConcept: 'किसी अवधारणा पर अटक गए हैं?',
		AITutorReady: "आपका एआई ट्यूटर बीजगणित या न्यूटन के नियमों को इस तरह से समझाने के लिए तैयार है जिसे आप पसंद करेंगे।",
		AskAITutor: 'एआई ट्यूटर से पूछें',
		YourSubjects: 'आपके विषय',
		ViewAll: 'सभी देखें',
		RecommendedForYou: 'आपके लिए अनुशंसित',
		Home: 'होम',
		Study: 'अध्ययन',
		AITutor: 'एआई ट्यूटर',
		Progress: 'प्रगति',

		// Progress Screen
		MyRewards: 'मेरे इनाम',
		Points: 'अंक',
		GreatJob: 'बहुत बढ़िया',
		TopPercent: 'आप इस सप्ताह शीर्ष 5% छात्रों में हैं। मास्टर एक्सप्लोरर बैज अनलॉक करने के लिए गति बनाए रखें!',
		ClaimDailyBonus: 'दैनिक बोनस प्राप्त करें',
		Level: 'स्तर',
		XPToLevel: 'अगले स्तर के लिए XP',
		MyBadges: 'मेरे बैज',
		BadgesUnlocked: 'बैज अनलॉक हुए',
		SevenDayStreak: '7-दिन का सिलसिला',
		UnlockedDaysAgo: '2 दिन पहले अनलॉक हुआ',
		MathWhiz: 'गणित विशेषज्ञ',
		PercentInGeometry: 'ज्यामिति में 100%',
		DoubtDestroyer: 'संदेह निवारक',
		ResolvedDoubts: '50 संदेह हल किए',
		Solution: 'समाधान',
		SolutionRead: 'समाधान पढ़ें',
		LeaderboardPreview: 'लीडरबोर्ड पूर्वावलोकन',
		ViewFullLeaderboard: 'पूरा लीडरबोर्ड देखें',
		You: 'आप',
		RisingStar: 'उभरता सितारा',

		// Profile Screen
		EditProfile: 'प्रोफ़ाइल संपादित करें',
		ChangeProfilePicture: 'प्रोफ़ाइल चित्र बदलें',
		FullName: 'पूरा नाम',
		FullNamePlaceholder: 'अपना पूरा नाम दर्ज करें',
		EmailAddress: 'ईमेल पता',
		ProfileEmailPlaceholder: 'अपना ईमेल दर्ज करें',
		MobileNumberLabel: 'मोबाइल नंबर',
		MobilePlaceholder: 'अपना मोबाइल नंबर दर्ज करें',
		CurrentClass: 'वर्तमान कक्षा',
		EducationalBoard: 'शैक्षिक बोर्ड',
		LanguagePreference: 'भाषा प्राथमिकता',
		ProfilePrivacyNote: 'आपकी प्रोफ़ाइल जानकारी का उपयोग आपकी सीखने की यात्रा और एआई ट्यूटर प्रतिक्रियाओं को व्यक्तिगत बनाने के लिए किया जाता है। हम आपके संपर्क विवरण कभी साझा नहीं करते हैं।',
		SaveChanges: 'बदलाव सहेजें',
		Logout: 'लॉगआउट',
	}
};

export default Strings;
